name: Run Terraform Docs
description: --

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: "${{ env.terraform_workingdir }}"
        output-file: README.md
        output-method: inject
        git-push: "true"
        args: --hide providers --hide requirements --hide modules --sort=false